### ISSUE TITLE
Iterm2 colorscheme with dark contrast = hard

### ISSUE THREAD

**Issue by gaynetdinov** [morhetz/gruvbox-contrib#17]
It there a way to set `hard` contrast for iterm2 version of this nice colorscheme? 

Thanks!

**Comment by krzkrzkrz** [comment]
You could do `let g:gruvbox_contrast_dark = 'hard'`

**Comment by morhetz** [comment]
Probably too late for answer, though it's changeable with iterm -> preferences -> profiles-> colors (`background` and `black`)

**Comment by WojtekKruszewski** [comment]
I suppose both "Background" and "Black" should be changed to `#fffdd8` for consistency?

![preferences_and_tig](https://cloud.githubusercontent.com/assets/54917/20210093/0bc66fd6-a7f8-11e6-9f16-c734a736ffbe.png)
