### ISSUE TITLE
Background colors look different on the new iterm build

### ISSUE THREAD

**Issue by krzkrzkrz** [morhetz/gruvbox-contrib#31]
iTerm2 build 3 has a different background color. I am using https://github.com/morhetz/gruvbox-contrib/blob/master/iterm2/gruvbox-dark.itermcolors for the iterm theme

Look at the following screenshot. Background colors are different 

<img width="1440" alt="screen shot 2016-06-04 at 8 45 41 am" src="https://cloud.githubusercontent.com/assets/390072/15798481/0a549428-2a32-11e6-9250-0fee71bed665.png">

Using Tmux and two seperate panes

Is that expected? Btw, I am using the fish shell. At `.config/fish/config.fish`. I have:

```
  set -l GRUVBOX_SCRIPT ~/.vim/bundle/gruvbox/gruvbox_256palette.sh
  if test -f $GRUVBOX_SCRIPT
    bash $GRUVBOX_SCRIPT
  end
```

**Comment by morhetz** [comment]
@krzkrzkrz could you check the updated iterm scheme?
this should be fixed with #26
