### ISSUE TITLE
Request: Gruvbox colorscheme for Gedit

### ISSUE THREAD

**Issue by kilbith** [morhetz/gruvbox-contrib#35]
Gruvbox is my favorite colorscheme on vim, I'd really love to see a theme for Gedit.

**Comment by kilbith** [comment]
Actually I managed to do that myself : https://github.com/morhetz/gruvbox-contrib/pull/36

**Comment by vanillajonathan** [comment]
I think it would be great if you could see if you could get this merged upstream.
https://gitlab.gnome.org/GNOME/gtksourceview

**Comment by vanillajonathan** [comment]
It would be great if this could be updated to be in sync with the latest version.
https://gitlab.gnome.org/GNOME/gtksourceview/-/blob/master/data/styles/Adwaita-dark.xml

It seems there has been some new additions of `def` statements.
