### ISSUE TITLE
Add Awesome WM and Vimperator theme

### ISSUE THREAD

**Issue by McSinyx** [morhetz/gruvbox-contrib#40]
I made a Gruvbox [Awesome](https://github.com/McSinyx/debdotfiles/tree/master/awesome/.config/awesome/themes/gruvbox) and [Vimperator](https://github.com/McSinyx/debdotfiles/tree/master/vimperator/.vimperator/colors) theme. How should those be added to this repo?

Thanks.

**Comment by morhetz** [comment]
Thanks! I have added links to the readme file

**Comment by McSinyx** [comment]
I'm switching to light gruvbox so a few themes are not maintained anymore. Could you update the links:

* Vimperator: https://github.com/McSinyx/debdotfiles/blob/edb2a03f5b793133e7618cb3c584cdc8fbbe9d9a/vimperator/.vimperator/colors/gruvbox.vimp
* GTK+ 2: https://github.com/McSinyx/debdotfiles/tree/33f963509eb04b956c0dfa1283d0a4d31c347bea/X/.themes/gruvnox
* Zathura:
    * Dark version: https://github.com/McSinyx/debdotfiles/blob/990b81ac195e7e0358beae14a5fdea4c4419ac7c/zathura/.config/zathura/zathurarc
    * Light one: https://github.com/McSinyx/debdotfiles/blob/a295db54fbe539abda4542195fa3b5781d13806d/zathura/.config/zathura/zathurarc

Also as *Raphael McSinyx* is just a fake (but unique) name, I think using just *McSinyx* to reference me is OK.
