### ISSUE TITLE
iTerm2 port is broken

### ISSUE THREAD

**Issue by dur-randir** [morhetz/gruvbox-contrib#49]
Commit bb665eecbfaaf8c3adc53f9025b24c83db30b4b0 broke iTerm2 styles. I could import & apply version from 164020e7967eaa60c87b135ceaccd22adf9c6853, but now it loads into iTerm but nothing happens when I try to switch to the style.

I'm running OS X 10.9.5 and iTerm2 2.1.4.

**Comment by morhetz** [comment]
That's probably because I was using 3.0 beta version.
It would be more suitable for me to drop 2.x compat, guess I'd need to leave deprecation notice somewhere.
I'm not sure I got you right though, does 164020e works ok for you?

**Comment by dur-randir** [comment]
>I'm not sure I got you right though, does 164020e works ok for you?

Yes, I've just re-checked and it imported & applied correctly.
