### ISSUE TITLE
i3, i3blocks, conky, and oomox gtk themes

### ISSUE THREAD

**Issue by a-schaefers** [morhetz/gruvbox-contrib#60]
I have adapted gruvbox dark mode for i3-wm, i3blocks, conky, and a matching oomox gtk theme, it turned out so well I thought you or others may like to know about it. You can have it if you want. Thanks for making gruvbox!

https://github.com/a-schaefers/i3-wm-gruvbox-theme

**Comment by morhetz** [comment]
@a-schaefers awesome
mind doing pull request adding link to the README file?

**Comment by a-schaefers** [comment]
Not at all ;-)
